=== nasa/FEI/src/jpl/mipl/mdms/FileService/komodo/client/resources/clienthelp.xsd
<?xml version = '1.0' encoding = 'UTF-8'?>
<xs:schema xmlns:xs = 'http://www.w3.org/2001/XMLSchema'>
	
  <xs:element name = 'KomodoHelp' type = 'KomodoHelpType' />

  <xs:complexType name = 'KomodoHelpType'>
    <xs:sequence>
      <xs:element ref = 'desc' maxOccurs = '1' />
      <xs:element ref = 'cmd' maxOccurs = 'unbounded' />
    </xs:sequence>
  </xs:complexType>

  <xs:element name = 'desc' type = 'xs:string' />
  <xs:element name = 'cmd' type = 'cmdType' />

  <xs:complexType name = 'cmdType'>
    <xs:sequence>
      <xs:element ref = 'desc' maxOccurs = '1' />
      <xs:element ref = 'usage' maxOccurs = '1' />
      <xs:element ref = 'params' maxOccurs = '1' />
    </xs:sequence>
    <xs:attribute name= 'name' type = 'xs:string' use = 'required' />
    <xs:attribute name= 'type' type = 'xs:string' use = 'required' />
    <xs:attribute name= 'alt' type = 'xs:string' use = 'optional' />
    <xs:attribute name= 'see_also' type = 'xs:string' use = 'optional' />
    <xs:attribute name= 'shortcut' type = 'xs:string' use = 'optional' />
  </xs:complexType>

  <xs:element name = 'usage' type = 'xs:string' />
  <xs:element name = 'params' type = 'paramsType' />

  <xs:complexType name = 'paramsType'>
    <xs:sequence>
      <xs:element ref = 'param' minOccurs = '0' maxOccurs = 'unbounded' />
    </xs:sequence>
  </xs:complexType>

  <xs:element name = 'param' type = 'paramType' />

  <xs:complexType name = 'paramType' mixed = 'true'>
    <xs:sequence>
      <xs:element ref = 'desc' maxOccurs = '1' />
    </xs:sequence>
    <xs:attribute name= 'name' type = 'xs:string' use = 'required' />
    <xs:attribute name= 'alt' type = 'xs:string' use = 'optional' />
  </xs:complexType>

</xs:schema>

=== nasa/FEI/src/jpl/mipl/mdms/FileService/komodo/client/resources/clienthelp.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<!-- $Id: clienthelp.xml,v 1.43 2010/06/30 16:39:09 ntt Exp $ -->
<KomodoHelp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!-- xsi:noNamespaceSchemaLocation = 'clienthelp.xsd'> -->
    <desc> Defines Komodo command help dictionary for use by Komodo clients. </desc>
    <cmd type="settings" name="echo">
        <desc>Session setting. Enables command output to terminal and log files.
            Setting echo off disables command output which is useful when using
            batch files that contain login information. Default is on.</desc>
        <usage>set echo {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="abort">
        <desc>Session setting. During processing of batch file abort when
            encountered an error. Default is off.</desc>
        <usage>set abort {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="safeRead">
        <desc>Session setting. When doing gets, write to a shadow directory
            while tranfering file, then move to final destination. Default is
            off.</desc>
        <usage>set safeRead {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="computeChecksum">
        <desc>Session setting. Compute a checksum before and after files are
            transmitted. If not the same, abort transaction and issue and error
            message. Default is off.</desc>
        <usage>set computeChecksum {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="autoDelete">
        <desc>Session setting. Deletes the local copy of a file after adding or
            replacing it in the FEI5 DB. Default is off.</desc>
        <usage>set autoDelete {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="log" see_also="logFile">
        <desc>Session setting. When on, fei commands and responses are logged to
            a file. Default is on, but if log file is not assigned, there is no
            logging</desc>
        <usage>set log {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="receipt">
        <desc>Session setting. When getting a file, a confirmation of receipt is
            logged in the database. Default is off.</desc>
        <usage>set receipt {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="replaceFile">
        <desc>Session setting. By default it won't overwrite a file in current
            working directory. Default is off.</desc>
        <usage>set replaceFile {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="preserve">
        <desc>Session setting. By default it won't overwrite the modification date 
             of a file in current in database for move. Default is on.</desc>
        <usage>set preserve {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="restart">
        <desc>Session setting. When on, getAfter command will track date of last
            download for given file type. Default is off.</desc>
        <usage>set restart {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="test">
        <desc>Session setting. When executing a batch file, check commands
            syntax but do not execute. Default is off.</desc>
        <usage>set test {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="timer">
        <desc>Session setting. When turned on each command is timed. Default is
            off.</desc>
        <usage>set timer {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="verbose">
        <desc>Session setting. Include files' size in bytes and date and time
            file was received along with the name. Default is off.</desc>
        <usage>set verbose {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="veryVerbose">
        <desc>Session setting. Along with verbose information show any comment,
            archive note or checksum associated with a file. Default is off.</desc>
        <usage>set veryVerbose {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="versionFile">
        <desc>Session setting. Creates versioning of existing files by appending
        filename with version information.  Default is off.</desc>
        <usage>set versionFile {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="diff">
        <desc>Session setting. Performs diff between existing file
        and new file to verify they are differnt before replacing
        or versioning.  Default is off.</desc>
        <usage>set diff {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="settings" name="replicate">
        <desc>Session setting. Enables replication, using
        the remote location of file from server as the local 
        location on client.  Default is off.</desc>
        <usage>set replicate {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="set">
        <desc>Set session settings. Parameters: abort, autoDelete,
            computeChecksum, log, receipt, replaceFile, restart, safeRead, test,
            timer, verbose, veryVerbose, echo, preserve, replicate, diff</desc>
        <usage>set &lt;parameter&gt; {on,off}</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="changePassword">
        <desc>Change user password in the database</desc>
        <usage>Interactive only, will be prompted</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="help">
        <desc>This help. help &lt;command name&gt; returns info on
            specific command. help types lists command types</desc>
        <usage>help [{&lt;command name&gt;,&lt;command
            type}&gt;]</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="version" shortcut="v">
        <desc>Show version of FEI client</desc>
        <usage>version</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="showDomainFile">
        <desc>Echos current domain file to screen</desc>
        <usage>showDomainFile</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="pwd">
        <desc>Show local working directory</desc>
        <usage>pwd</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="ls">
        <desc>List contents of local directory</desc>
        <usage>ls</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="login">
        <desc>Enter user name and password, will prompt interactively if not in
            batch mode</desc>
        <usage>login [&lt;name&gt;] [&lt;password&gt;]</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="logFile">
        <desc>Assign name of a log file.</desc>
        <usage>logFile &lt;file&gt;</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="dateFormat">
        <desc>Set or print the date/time format.</desc>
        <usage>dateFormate [&quot;&lt;format&gt;&quot;]</usage>
        <params>
            <param name="format">
                <desc>Date format string.  See SimpleDateFormat javadoscs 
                    for examples.</desc>
            </param>
        </params>
    </cmd>
    <cmd type="utility" name="logCmds">
        <desc>Log commands to a file</desc>
        <usage>logCmds &lt;file&gt;</usage>
        <params>
            <param name="file">
                <desc>The name of the file to which commands are logged</desc>
            </param>
        </params>
    </cmd>
    <cmd type="utility" name="pause">
        <desc>Stops executing a batch script until the &lt;return&gt;
            key is pressed</desc>
        <usage>pause</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="cd">
        <desc>Change local working directory</desc>
        <usage>cd [&lt;local directory&gt;]</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="bye" alt="quit, exit">
        <desc>Exit fei client</desc>
        <usage>bye</usage>
        <params/>
    </cmd>
    <cmd type="utility" name="batch">
        <desc>Read a sequence of FEI commands from a file.</desc>
        <usage>batch &lt;file name&gt; [{repeatAt hh:mm {am,pm},
            repeatEvery hh:mm [hh:mm {am,pm}}]</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="unlockFileType">
        <desc>Unlock current file type for given group or owner</desc>
        <usage>unlockFileType {group,owner}</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="showTypes">
        <desc>Show available file types</desc>
        <usage>showTypes</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="showSince">
        <desc>Show files added to current file type since specified time
            (Deprecated)</desc>
        <usage>showSince &lt;yyyy-MM-ddThh:mm:ss.SSS&gt; [invoke
            "&lt;system command&gt;"]</usage>
        <params/>
    </cmd>
    <cmd type="vft" name="showVFT">
        <desc>Show available vfts. If vft is specified, show details.</desc>
        <usage>showVFT [&lt;vft name&gt;]
            [&lt;yyyy-MM-ddThh:mm:ss.SSS&gt;]</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="showLatest">
        <desc>Show latest files added to current file type</desc>
        <usage>showLatest [&lt;file name expression&gt;] [invoke
            "&lt;system command&gt;"]</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="showCapabilities">
        <desc>Show user's capabilities for given file type</desc>
        <usage>showCapabilities &lt;file type&gt;</usage>
        <params/>
    </cmd>
    <cmd type="filetype" name="showBetween">
        <desc>Show files added to current file type during specified time range</desc>
        <usage>showBetween &lt;yyyy-MM-ddThh:mm:ss.SSS&gt; and
            &lt;yyyy-MM-ddThh:mm:ss.SSS&gt; [invoke "&lt;system
            command&gt;"]</usage>
        <params/>
    </cmd>
