=== nasa/FEI/src/jpl/mipl/mdms/test/db/dbInterface.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- CVS: $Id: dbInterface.xsd,v 1.1.1.1 2003/01/25 02:18:52 txh Exp $ -->

<!-- MDMS XML Schema Definition for dbInterface.xml file -->

<!-- Copyright 2001, California Institute of Technology. -->
<!-- ALL RIGHTS RESERVED.                                -->
<!-- U.S. Government Sponsorship acknowledge. 6/29/2000. -->
<!-- MIPL Data Management System (MDMS).                 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://sorrento.jpl.nasa.gov"
    targetNamespace="http://sorrento.jpl.nasa.gov"
    elementFormDefault="qualified"
>

<xs:element name="database">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="connection" />
            <xs:element ref="setup" />
            <xs:element ref="showRecords" />
            <xs:element ref="deleteRecord" />
            <xs:element ref="simpleProc" />
            <xs:element ref="cleanup" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="connection">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="jdbc" />
            <xs:element ref="jndi" />
            <xs:attribute name="title" type="xs:string" use="required" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="jdbc">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="driver" maxOccurs="1" type="xs:string" />
            <xs:element name="url" maxOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="jndi">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="host" maxOccurs="1" type="xs:string" />
            <xs:element name="port" maxOccurs="1" type="xs:string" />
            <xs:element name="searchBase" maxOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="setup">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="defineTables" />
            <xs:element ref="defineProcedures" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="defineTables">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="prep" maxOccurs="unbounded" type="xs:string" />
            <xs:element name="statement" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="defineProcedures">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="prep" maxOccurs="unbounded" type="xs:string" />
            <xs:element name="statement" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="showRecords">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="statement" maxOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="deleteRecord">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="statement" maxOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="simpleProc">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="procedure" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="cleanup">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="dropTables" />
            <xs:element ref="dropProcedures" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="dropTables">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="statement" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="dropProcedures">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="statement" maxOccurs="unbounded" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== nasa/FEI/src/jpl/mipl/mdms/test/db/mysqlInterface.xml
<?xml version="1.0"?>
<!-- CVS: $Id: mysqlInterface.xml,v 1.1.1.1 2003/01/25 02:18:52 txh Exp $ -->

<!-- MDMS XML interface to relational database back-end. -->

<!-- Copyright 2001, California Institute of Technology. -->
<!-- ALL RIGHTS RESERVED.                                -->
<!-- U.S. Government Sponsorship acknowledge. 6/29/2000. -->
<!-- MIPL Data Management System (MDMS).                 -->

<database xmlns:xsi="http://www.w3.org/1999/XMLSchema/instance"
    xmlns="http://sorrento.jpl.nasa.gov"
    xsi:schemaLocation="http://sorrento.jpl.nasa.gov/schema/dbInterface.xsd"
>
    <connection title="MySQL JNDI and JDBC Connection">
        <jdbc>
            <driver>
                org.gjt.mm.mysql.Driver
            </driver>
            <url>
                jdbc:mysql://@host:@port/
            </url>
        </jdbc>
        <jndi>
            <host>
                phoenix.jpl.nasa.gov
            </host>
            <port>
                389
            </port>
            <searchBase>
                dc=mdms,dc=jpl,dc=nasa,dc=gov
            </searchBase>
        </jndi>
    </connection>

    <setup>
        <defineTables>
            <prep>
            </prep>
            <statement>
                create table if not exists simpleTable (roleIdx int auto_increment primary key not null, name varchar(30) not null, getFlag bit not null, addFlag bit not null, deleteFlag bit not null, replaceFlag bit not null, proprietaryGet bit not null, description varchar(120) null)
            </statement>
        </defineTables>
        <defineProcedures>
            <prep>
            </prep>
            <statement>
            </statement>
        </defineProcedures>
    </setup>

    <showRecords>
        <statement>
            select @list from @table
        </statement>
    </showRecords>

    <deleteRecord>
        <statement>
            delete from @table where @list
        </statement>
    </deleteRecord>

    <simpleProc>
        <procedure>
            insert into simpleTable (name, getFlag, addFlag, deleteFlag, replaceFlag, proprietaryGet, description) values ('@name', @getFlag, @addFlag, @delFlag, @rplFlag, @proprietaryGet, '@description')
        </procedure>
    </simpleProc>

    <cleanup>
        <dropTables>
            <statement>
                drop table if exists simpleTable
            </statement>
        </dropTables>
        <dropProcedures>
            <statement>
            </statement>
        </dropProcedures>
    </cleanup>
</database>

=== nasa/FEI/src/jpl/mipl/mdms/test/db/sybaseInterface.xml
<?xml version="1.0"?>
<!-- CVS: $Id: sybaseInterface.xml,v 1.1.1.1 2003/01/25 02:18:52 txh Exp $ -->

<!-- MDMS XML interface to relational database back-end. -->

<!-- Copyright 2001, California Institute of Technology. -->
<!-- ALL RIGHTS RESERVED.                                -->
<!-- U.S. Government Sponsorship acknowledge. 6/29/2000. -->
<!-- MIPL Data Management System (MDMS).                 -->

<database xmlns:xsi="http://www.w3.org/1999/XMLSchema/instance"
    xmlns="http://sorrento.jpl.nasa.gov"
    xsi:schemaLocation="http://sorrento.jpl.nasa.gov/schema/dbInterface.xsd"
>
    <connection title="Sybase JDBC and JNDI Connection Parameters">
        <jdbc>
            <driver>
                com.sybase.jdbc2.jdbc.SybDriver
            </driver>
            <url>
                jdbc:sybase:Tds:@host:@port
            </url>
        </jdbc>
        <jndi>
            <host>
                @host
            </host>
            <port>
                @port
            </port>
            <searchBase>
                dc=mdms,dc=jpl,dc=nasa,dc=gov
            </searchBase>
        </jndi>
    </connection>

    <setup>
        <defineTables>
            <prep>
                if exists (select * from sysobjects where name = 'simpleTable') drop table simpleTable
            </prep>
            <statement>
                create table simpleTable (roleIdx numeric(10,0) identity, name varchar(30) not null, getFlag bit not null, addFlag bit not null, deleteFlag bit not null, replaceFlag bit not null, proprietaryGet bit not null, description varchar(120) null, constraint accessRolesPK1 primary key (roleIdx))
            </statement>
        </defineTables>
        <defineProcedures>
            <prep>
                if exists (select * from sysobjects where name = 'simpleProc') drop procedure simpleProc
            </prep>
            <statement>
                create procedure simpleProc @name varchar(30), @getFlag bit = 1, @addFlag bit = 0, @rplFlag bit = 0, @delFlag bit = 0, @proprietaryGet bit = 0, @description varchar(120) = null as begin insert into simpleTable (name, getFlag, addFlag, deleteFlag, replaceFlag, proprietaryGet, description) values (@name, @getFlag, @addFlag, @delFlag, @rplFlag, @proprietaryGet, @description) end
            </statement>
        </defineProcedures>
    </setup>

    <showRecords>
        <statement>
            select @list from @table
        </statement>
    </showRecords>

    <deleteRecord>
        <statement>
            delete from @table where @list
        </statement>
    </deleteRecord>

    <simpleProc>
        <procedure>
            simpleProc '@name', @getFlag, @addFlag, @delFlag, @rplFlag, @proprietaryGet, '@description'
        </procedure>
    </simpleProc>

    <cleanup>
        <dropTables>
            <statement>
                if exists (select * from sysobjects where name = 'simpleTable') drop table simpleTable
            </statement>
        </dropTables>
        <dropProcedures>
            <statement>
                if exists (select * from sysobjects where name = 'simpleProc') drop procedure simpleProc
            </statement>
        </dropProcedures>
    </cleanup>
</database>
